In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


# create tensors

## scalar, vector, matrix, tensor

In [ ]:
# scalar
scalar = torch.tensor(7)
print(scalar.ndim)
# scalar has no ndim
print(scalar.item())

In [ ]:
#vector
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)

In [ ]:
#matrix
matrix = torch.tensor([[7,8],[9,10]])
print(matrix.ndim)
print(matrix.shape)
print(matrix[0])

In [ ]:
# tensor
tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
print(tensor.ndim)
print(tensor.shape)
print(tensor[0][2][1])

## random tensors

In [ ]:
random_tensor = torch.rand(2, 3, 4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor[1][2][1])

In [ ]:
# reproducbility
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A,random_tensor_B,random_tensor_A == random_tensor_B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
random_image_size_tensor = torch.rand(size = (3,224,224)) # color channels(R,G,B), height, width

print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

In [ ]:
from torchvision import transforms

# 方法 A：使用 torchvision 的内置工具（最省事）
show_img = transforms.ToPILImage()(random_image_size_tensor)
show_img.show() # 调用系统图片查看器打开

## zeros and ones

In [ ]:
zeros = torch.zeros(size = (3,4))
print(zeros)
print(zeros.ndim)
print(zeros.shape)

In [ ]:
ones = torch.ones(size = (3,4))
print(ones)
print(ones.ndim)
print(ones.shape)
print(ones.dtype)

## range and steps of tensors

In [ ]:
one_to_ten= torch.arange(1,11)
step= torch.arange(start=0,end = 1, step = 0.15)

one_to_ten,step

## tensors like

In [ ]:
ten_zeros = torch.zeros_like(input = step)
ten_ones = torch.ones_like(input = step)
ten_empty = torch.empty_like(input = step)
ten_rand = torch.rand_like(input = step)
ten_randn = torch.randn_like(input = step)
ten_randint = torch.randint_like(input = step, low= 5, high= 10)
ten_full = torch.full_like(input = step,fill_value=7)

print("zeros_like:",ten_zeros)
print("ones_like:",ten_ones)
print("empty_like:",ten_empty)
print("rand_like:",ten_rand)
print("randn_like:",ten_randn)
print("randint_like:",ten_randint)
print("full_like:",ten_full)


## setting tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0,6,9],
                               dtype = None, # data type
                               device = None, # device type: cpu, cuda, mps, xpu
                               requires_grad=False) # Is True if gradients need to be computed for this Tensor, False otherwise.
print(float_32_tensor.dtype)
float_16_tensor = torch.tensor([1.0,6,9],dtype = torch.float16)
print(float_16_tensor.dtype)
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor.dtype)
print(float_16_tensor)


In [ ]:
float_16_tensor * float_32_tensor # sometimes it works

# Tensor oprations
## get attributes

In [ ]:
some_tensor = torch.rand(3,4)
print(some_tensor)
# get dtype
print("datatype:",some_tensor.dtype)
print("complex: ",some_tensor.is_complex())
print("floating: ",some_tensor.is_floating_point())

# shape
print("shape:",some_tensor.shape)

#device
print("device:",some_tensor.device)
print("cpu:",some_tensor.is_cpu)


## manipulating tensors

In [ ]:
tensor1 = torch.tensor([1,2,3])

print("addition:")
print(tensor1 + 10)
print(tensor1.add(10))
print(torch.add(tensor1,10))

print("subtraction")
print(tensor1 - 10)
print(torch.sub(tensor1,2))

print("element multiplication")
print(tensor1 * 10)
print(torch.mul(tensor1,10))
print(tensor1 * tensor1)

print("division")
print(tensor1 / 2)
print(tensor1.div(2))


print("matrix multiplication")
print(tensor1 @ tensor1)
print(torch.matmul(tensor1, tensor1))



In [ ]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]]) # 3,2
tensor_B = torch.tensor([[7,10],[8,11],[9,12]]) # 3,2

# transpose
print(torch.mm(tensor_A, tensor_B.T)) # alias of matmul
print(torch.mm(tensor_A.T, tensor_B)) # alias of matmul


## tensor reshape

In [4]:
x = torch.arange(1,10)
print(x,x.shape)
x_reshaped = x.reshape(3,3)
print(x_reshaped)
z = x.view(9,1)
print(z.shape,x.shape)
z[0,:] = 5
print(x) # z and x use the same memory

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([9, 1]) torch.Size([9])
tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])


In [5]:
# stack
x_cat = torch.cat([x,x,x,x],dim = 0) # don't add dimension
print(x_cat)
x_stacked = torch.stack([x,x,x,x],dim=0) # add dimension
print(x_stacked)

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6,
        7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])


In [7]:
# squeeze: Returns a tensor with all specified dimensions of input of size 1 removed.
x_zeros = torch.zeros(2,1,2,1,2)
print(x_zeros,x_zeros.shape)
print(x_zeros.squeeze().shape)

print(x_cat.shape)

print(x_cat.unsqueeze(dim = 0).shape)
print(x_cat.unsqueeze(dim = 1).shape)


tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]]) torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([36])
torch.Size([1, 36])
torch.Size([36, 1])


In [13]:
#permute
random_image = torch.rand(size = (224,512,3)) #  height, width,color channels(R,G,B)
random_image_tensor = torch.permute(random_image,(2,0,1))
print(random_image_tensor.shape)


torch.Size([3, 224, 512])


## indexing(same as NumPy)


In [24]:
x = torch.arange(1,10).reshape(1,3,3)
print(x,x.shape,"\n-----------\n", x[0], x[0][0],x[0][0][0])
print("\n-----------\n",x[:,:,1],x[0,0,:])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3]) 
-----------
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) tensor([1, 2, 3]) tensor(1)

-----------
 tensor([[2, 5, 8]]) tensor([1, 2, 3])


# tensor aggragation

In [7]:
x = torch.arange(0,100,10)
print(torch.min(x), "," , x.min())
print(torch.max(x), "," , x.max())
print(torch.argmin(x), "," , x.argmin())
print(torch.argmax(x), "," , x.argmax())
print(torch.mean(x.type(torch.float32)), "," , x.type(torch.float32).mean())# requires float or complex datatype
print(torch.sum(x), "," , x.sum())


tensor(0) , tensor(0)
tensor(90) , tensor(90)
tensor(0) , tensor(0)
tensor(9) , tensor(9)
tensor(45.) , tensor(45.)
tensor(450) , tensor(450)


# Numpy to Pytorch tensor

In [ ]:
import numpy as np
# numpy to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
print(array,array.dtype, tensor) # array is float64
tensor = torch.from_numpy(array).type(torch.float32)
print(tensor.dtype) # change to float32
# change array won'r impact tensor

[1. 2. 3. 4. 5. 6. 7.] float64 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
torch.float32


In [ ]:
# tensor to numpy
tensor = torch.ones(7)
array = tensor.numpy()
print(array,array.dtype, tensor) # array is float32


[1. 1. 1. 1. 1. 1. 1.] float32 tensor([1., 1., 1., 1., 1., 1., 1.])


# run tensor on GPU(Colab cuda)
also can buy GPU and run locally. or buy GCP services - GCP, AWS, Azure

In [2]:
!nvidia-smi

Fri Apr 17 04:51:56 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# check if cuda is available
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# check how many device can be used
torch.cuda.device_count()

1

In [8]:
tensor = torch.tensor([1,2,3])
print(tensor.device)

# put tensors on GPU
tensor_gpu = tensor.to(device)
print(tensor_gpu.device)

# put tensors on CPU(for numpy most of time)
tensor_cpu = tensor_gpu.cpu().numpy()
print(tensor_cpu)


cpu
cuda:0
[1 2 3]
