# Matrics: 2-D structure

In [90]:
import numpy as np


In [91]:
# create matrix
matrix = np.array([[1,2,3],[4,5,6]]) # direct create
my_list = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
matrix = np.array(my_list)
print(type(matrix))
print("my_list:",matrix)

#change back to list
new_list= matrix.tolist()
print(type(matrix))
print(type(new_list))




<class 'numpy.ndarray'>
my_list: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
<class 'list'>


In [92]:
# get value
print("original:",matrix)
print("matrix[0]:",matrix[0])
matrix[0] = np.array([3,2,1])
print("matrix[0]:",matrix[0])
print("[2][1]:",matrix[2][1])
print("[2,1]:",matrix[2,1])
matrix[2,1] = 100
print("new value:", matrix[2,1])

#get row or column
print("row 2:", matrix[:,2])

# get statistics
print("sum:",matrix.sum())
print("sum for row: ",matrix.sum(axis = 0)) # sum elements for every row
print("sum for column:",matrix.sum(axis = 1)) # sum elements for every column
print("aver for row:",matrix.mean(axis = 0)) 
print("max for row:", matrix.max(axis = 0)) 



original: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
matrix[0]: [1 2 3]
matrix[0]: [3 2 1]
[2][1]: 8
[2,1]: 8
new value: 100
row 2: [ 1  6  9 12]
sum: 170
sum for row:  [ 24 118  28]
sum for column: [  6  15 116  33]
aver for row: [ 6.  29.5  7. ]
max for row: [ 10 100  12]


In [93]:
# create special metrics
print(np.zeros((3,2)))
print(np.ones((3,2))*2)
print(np.eye(3))


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [112]:
# boolean vectors to metrics
bi_vectors = np.array([True, False, True, True, False, True])
bi_matrics = bi_vectors.reshape(3,-1)
print(bi_matrics)
print(bi_matrics.shape)

# boolean metrics from conditional
bi_answers = matrix % 3 != 0
print(bi_answers)

print(bi_answers.all()) # and of all elements
print(bi_answers.any()) # or of all elements

print(bi_answers.all(axis = 0)) # see if any value is False
print(bi_answers.all(axis = 1)) # see if any value is False

nan_matrix = np.array([[np.nan,2,3],[4,np.nan,6]])
print("Original:", nan_matrix)
print("which elemnt is NaN: ",np.isnan(nan_matrix))
print("If there is any NaN?",np.isnan(nan_matrix).any())


[[ True False]
 [ True  True]
 [False  True]]
(3, 2)
[[False  True  True]
 [ True  True False]
 [ True  True False]
 [ True  True False]]
False
True
[False  True False]
[False False False False]
Original: [[nan  2.  3.]
 [ 4. nan  6.]]
which elemnt is NaN:  [[ True False False]
 [False  True False]]
If there is any NaN? True


# attributes

In [95]:
print("dimension:", matrix.ndim)
print("dtype:", matrix.dtype)
print("size:", matrix.size)
print("shape:", matrix.shape) # 4rows and 3 columns
print("rows:", matrix.shape[0])
print("columns:", matrix.shape[1])


dimension: 2
dtype: int64
size: 12
shape: (4, 3)
rows: 4
columns: 3


## 1-D vector change to 2-D metrix

In [96]:
vector = np.arange(5)
print("1-D shape:",vector.shape)
row_vec = vector[np.newaxis,:]
col_vec = vector[:, np.newaxis]
print("2-D row side:",row_vec.shape)
print("2-D column side:",col_vec.shape)



1-D shape: (5,)
2-D row side: (1, 5)
2-D column side: (5, 1)


## change shape

In [97]:
vector = np.arange(1,5)
print("original:", vector)
print("reshape(2,2):", vector.reshape(2,2))
print("reshape(2,-1):", vector.reshape(2,-1)) # when only know number of rows, if it cannot, will return error
print("reshape(1,4):", vector.reshape(1,4))
print("reshape(4,1):", vector.reshape(4,1))
# these are views

original: [1 2 3 4]
reshape(2,2): [[1 2]
 [3 4]]
reshape(2,-1): [[1 2]
 [3 4]]
reshape(1,4): [[1 2 3 4]]
reshape(4,1): [[1]
 [2]
 [3]
 [4]]


## 2-D flatten to 1-D

In [98]:

matrix2 = np.array([[1,2,3],[4,5,6]])
print("original:", matrix2)
print("matrix reshape: ",matrix2.reshape(-1)) # create view
flatten = matrix2.flatten()
print("matrix flatten: ",flatten) # create copy

original: [[1 2 3]
 [4 5 6]]
matrix reshape:  [1 2 3 4 5 6]
matrix flatten:  [1 2 3 4 5 6]
