# 05 Exercise - Making and Modifying Matrices

In this exercise set, we are going are going to work with a dataset about the weather in Berlin. This will give us plenty of practice with 2D arrays.

In [1]:
# DON'T MODIFY THIS CELL, ONLY RUN IT.

# Importing numpy as np.
import numpy as np

# List of weather in Berlin in Celsius taken from Wikipedia
row_description = ["Record High", "Daily Mean", "Record Low"]
berlin_weather_list = [
    [15.1, 18.0, 25.8, 30.8, 32.7, 35.4, 37.3, 38.0, 32.3, 27.7, 20.4, 15.6], 
    [0.1, 0.9, 43, 9.0, 14.0, 16.8, 19.1, 18.5, 14.2, 9.4, 4.4, 1.0],
    [-25.3, -22.0, -16.0, -7.4, -2.8, 1.3, 4.9, 4.6, -0.9, -7.7, -12.0, -24.0]
]

# Print out the data
for idx, row in enumerate(row_description):
    print(f'{row}:\n{berlin_weather_list[idx]}\n')

Record High:
[15.1, 18.0, 25.8, 30.8, 32.7, 35.4, 37.3, 38.0, 32.3, 27.7, 20.4, 15.6]

Daily Mean:
[0.1, 0.9, 43, 9.0, 14.0, 16.8, 19.1, 18.5, 14.2, 9.4, 4.4, 1.0]

Record Low:
[-25.3, -22.0, -16.0, -7.4, -2.8, 1.3, 4.9, 4.6, -0.9, -7.7, -12.0, -24.0]



## Exercise 1: Make a 2D Array

Make a 2D array called <b>berlin_weather</b> from the <b>berlin_weather_list</b> and check the size of the array.

In [6]:
# Convert the berlin_weather_list into a NumPy array
berlin_weather = np.array(berlin_weather_list)
# Find the shape of the array
print(berlin_weather.shape)


(3, 12)


## Exercise 2: Changing Enteries

There is a typo in the dataset. The average temperature for March daily average should be 4.3 not 43. Fix the mistake by using indexing, not by modifying the original list.

In [7]:
# Setting the daily average for March to be 4.3
berlin_weather[1,2] = 4.3
print(berlin_weather)

[[ 15.1  18.   25.8  30.8  32.7  35.4  37.3  38.   32.3  27.7  20.4  15.6]
 [  0.1   0.9   4.3   9.   14.   16.8  19.1  18.5  14.2   9.4   4.4   1. ]
 [-25.3 -22.  -16.   -7.4  -2.8   1.3   4.9   4.6  -0.9  -7.7 -12.  -24. ]]


## Exercise 3:  Printing Out the Data

Print out the column containing the data for June.

In [8]:
# Data for June
print(berlin_weather[:,5])

[35.4 16.8  1.3]


## Exercise 4: Reshaping the Data

### Exercise 4a: 
Take the row containing the record low temperatures and reshape it into a matrix with 6 rows and 2 columns.

In [9]:
# Reshape the record low temperatures
record_low = berlin_weather[2].reshape(6,-1)
print(record_low)

[[-25.3 -22. ]
 [-16.   -7.4]
 [ -2.8   1.3]
 [  4.9   4.6]
 [ -0.9  -7.7]
 [-12.  -24. ]]


### Exercise 4b: 
Take average of pairs of consecutive months of the record low temeratures.

<i>Hint: </i> Use what you found in Exercise 4a and the mean method.

In [11]:
# Take average of pairs of consecutive months.
low_aver = np.mean(record_low,axis = 1)
print(low_aver)

[-23.65 -11.7   -0.75   4.75  -4.3  -18.  ]


## Exercise 5: Max and Min
Find the maximum and minimum values over all the rows.

In [14]:
# The max over all the rows
low_max = np.max(berlin_weather,axis = 1)
print(low_max)

[38.  19.1  4.9]


In [15]:
# The min over all the rows
low_min = np.min(berlin_weather,axis = 1)
print(low_min)

[ 15.1   0.1 -25.3]


## Exercise 6: Boolean Matrices

### Exercise 6a: 
For how many rows are the average temperature over 10 degrees Celsius?

In [16]:
# The total number of months with average over 10 degrees Celsius
over10 = berlin_weather[1] > 10
print(sum(over10))

5


### Exercise 6b: 
Are there months where the record high is subzero?

In [17]:
# Any record highs below zero?
below0 = berlin_weather[0] < 0
print(below0.any())


False


What about months where the daily average is subzero?

In [18]:
# Any averages below zero?
below0_aver = berlin_weather[1] < 0
print(below0_aver.any())

False


## Moral of the Story

In this exercise set, we have seen that reshaping and other techniques are vital for handeling data. Being comfortable with matricies in NumPy is a valuable skill. 