In [3]:
import numpy as np
from numpy import linalg # package for liner Algebra
# The vectors we are going to use in this module.
first_vector = np.array([1, 2, 4])
second_vector = np.array([2, -1, 9])
# The matrices we are going to use in this module.
first_matrix = np.array([[1, 2, 0], [3, 10, -2], [-3, 5, 3]])
second_matrix = np.array([[1, 2, 0], [0, 0, -2], [-3, 8, 3]])
print("vectors:", first_vector,second_vector)
print("matrix:\n", first_matrix,"\n")
print(second_matrix)

vectors: [1 2 4] [ 2 -1  9]
matrix:
 [[ 1  2  0]
 [ 3 10 -2]
 [-3  5  3]] 

[[ 1  2  0]
 [ 0  0 -2]
 [-3  8  3]]


# Product
## pointwise multiplication

In [4]:
print("vector * vector: ", first_vector * second_vector)
print("matrix * matrix: ", first_matrix * second_matrix)

vector * vector:  [ 2 -2 36]
matrix * matrix:  [[ 1  4  0]
 [ 0  0  4]
 [ 9 40  9]]


## Dot product
### vector

In [5]:
print(first_vector)
print(second_vector)
np.dot(first_vector,second_vector)

[1 2 4]
[ 2 -1  9]


np.int64(36)

In [6]:
def are_orthogonal(vect1,vect2):
    return np.dot(vect1,vect2) ==0

### matrix

In [7]:
print(first_matrix)
print(np.eye(3) @ first_matrix)
print(second_matrix)
print(np.dot(first_matrix,second_matrix))
print(first_matrix @ second_matrix)
print(np.matmul(first_matrix,second_matrix))

[[ 1  2  0]
 [ 3 10 -2]
 [-3  5  3]]
[[ 1.  2.  0.]
 [ 3. 10. -2.]
 [-3.  5.  3.]]
[[ 1  2  0]
 [ 0  0 -2]
 [-3  8  3]]
[[  1   2  -4]
 [  9 -10 -26]
 [-12  18  -1]]
[[  1   2  -4]
 [  9 -10 -26]
 [-12  18  -1]]
[[  1   2  -4]
 [  9 -10 -26]
 [-12  18  -1]]


In [8]:
# matrix power
print(first_matrix @ first_matrix @ first_matrix @ first_matrix)
print(linalg.matrix_power(first_matrix,4))

[[  895  2030  -596]
 [ 3939  8540 -2626]
 [ 2319  5671 -1545]]
[[  895  2030  -596]
 [ 3939  8540 -2626]
 [ 2319  5671 -1545]]


## Cross product

In [9]:
fscross = np.cross(first_vector, second_vector)
print(fscross)
print(np.dot(first_vector,fscross))
print(np.dot(second_vector,fscross))

[22 -1 -5]
0
0


In [10]:
vec1 = np.arange(2)
vec2 = np.arange(1,3)
print(vec1)
print(vec2)
print(np.cross(vec1,vec2))


[0 1]
[1 2]
-1


/var/folders/ln/sf2_fvgd1yg8tqlyqdc5bdh40000gn/T/ipykernel_3492/1541846914.py:5: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(vec1,vec2))


# attributes from linalg
## norm

In [11]:
# Norm
print("first_vector norm",linalg.norm(first_vector))
print("second vector norm",linalg.norm(second_vector))

print("first_matrix norm",linalg.norm(first_matrix))


first_vector norm 4.58257569495584
second vector norm 9.273618495495704
first_matrix norm 12.68857754044952


In [12]:
def angle(vec1,vec2):
    cos_angle = np.dot(vec1,vec2)/(linalg.norm(vec1) * linalg.norm(vec2))
    return np.arccos(cos_angle)

In [13]:

print(angle(first_vector,second_vector))

print(angle(first_matrix,second_matrix))


0.5602591049467773
[[1.56253459 1.55427229 1.60384891]
 [1.49637287 1.65350702 1.78728613]
 [1.67009915 1.42153314 1.57905806]]


## Determinant
if det is 0, it is not invertable. If det is non zero, it is invertable

In [17]:
print(linalg.det(first_matrix))
print(linalg.det(second_matrix))

non_invertible = np.array([[1,2,0],[-2,10,3],[-3,8,3]])
print(linalg.det(non_invertible))
print(np.around(linalg.det(non_invertible)))


33.99999999999999
28.00000000000001
3.108624468950436e-15
0.0


## Inverse

In [21]:
print(np.around(linalg.inv(first_matrix) @ first_matrix,10)) # np.dot

print(linalg.inv(second_matrix))

[[ 1. -0. -0.]
 [-0.  1.  0.]
 [ 0. -0.  1.]]
[[ 0.57142857 -0.21428571 -0.14285714]
 [ 0.21428571  0.10714286  0.07142857]
 [-0.         -0.5        -0.        ]]


In [28]:
# Ax = b, x = A-1 * b
x1= linalg.solve(first_matrix,first_vector)
print(x1)

print(first_matrix @ x1) # equal to first_vector

# no solution
x2= linalg.solve(non_invertible,first_vector)
print(x2)

print(non_invertible @ x2) # not equal to first_vector

# infinate solution

third_vector = np.array([1,-2,-3])
x3= linalg.solve(non_invertible,third_vector)
print(x3)

print(non_invertible @ x3) # equal to third_vector but not the noly solution

[0.35294118 0.32352941 1.14705882]
[1. 2. 4.]
[ 5.79034238e+15 -2.89517119e+15  1.35107989e+16]
[-2. 10. 10.]
[1. 0. 0.]
[ 1. -2. -3.]
