# 07 Exercise - Basic Linear Algebra

This exercise set is all about doing standard linear algebra exercises using NumPy. 

In [1]:
#DON'T MODIFY THIS CELL, ONLY RUN IT.

# Importing NumPy as np.
import numpy as np

## Exercise 1: Import the Linalg Submodule

In [2]:
# Importing the linalg submodule from NumPy
from numpy import linalg

## Exercise 2: Simple Vector Operations

### Exercise 2a: 
Are any of the vectors $[1, 2, 3]$  and $[2, 3, 4]$  parallel? What about orthogonal?

In [21]:
# Make the vectors
v1 = np.array([1,2,3])
v2 = np.array([2,3,4])
# Checking if parallel
print(np.cross(v1,v2))
# Checking if orthogonal
print(np.dot(v1,v2))

[-1  2 -1]
20


### Exercise 2b: 
Can you find the angle between the vector $[1, 2, 3]$ and $[2, 3, 4]$?

In [9]:
# Defining the angle function
def angle(vec1,vec2):
    cos_angle =np.dot(vec1,vec2)/(linalg.norm(vec1) * linalg.norm(vec2))
    return np.arccos(cos_angle)
# Finding the angle
print(angle(v1,v2))

0.12186756768575456


## Exercise 3: Simple Matrix Operations

Define the matrices 
$$ A= 
\begin{bmatrix}
1&1&2\\
1&1&1\\
1&1&1
\end{bmatrix}\quad \text{and}\quad B= 
\begin{bmatrix}
1&0&0\\
0&1&-2\\
0&0&1
\end{bmatrix}.
$$

### Exercise 3a: 
Find the matrix product $AB$.

In [10]:
# Defining the matrices
matrix_a = np.array([[1,1,2],[1,1,1],[1,1,1]])
matrix_b = np.array([[1,0,0],[0,1,-2],[0,0,1]])
# Finding the matrix product AB
print(matrix_a @ matrix_b)

[[ 1  1  0]
 [ 1  1 -1]
 [ 1  1 -1]]


### Exercise 3b: 
Find the matrix product $B^{-1}A^5$.

In [12]:
# Find the matrix power
result = linalg.inv(matrix_b) @ linalg.matrix_power(matrix_a,5)
print(result)

[[142. 142. 185.]
 [327. 327. 426.]
 [109. 109. 142.]]


### Exercise 3c: 
Find the transpose of $A$, namely $A^T$. Compute the product $A A^T$.

In [13]:
# Finding the transpose of $A$
matrix_a_t = np.transpose(matrix_a)
print(matrix_a_t)
# Finding the product of $AA^T$
result2 = matrix_a @ matrix_a_t
print(result2)

[[1 1 1]
 [1 1 1]
 [2 1 1]]
[[6 4 4]
 [4 3 3]
 [4 3 3]]


## Exercise 4: Balancing Chemical Equations

In this exercise we are going to use NumPy to balance a set of chemical equations. The question is how to balance the equation
$$x*C_4H_{10}+y*O_2 = v*H_2O + w*CO_2.$$
Written as vectors this becomes
$$x*[4,10,0]+y*[0,0,2]=z*[0,2,1] + w*[1,0,2],$$
or equivalently,
$$
\begin{bmatrix}
4&0&0\\
10&0&-2\\
0&2&-1
\end{bmatrix}
\begin{bmatrix}
x\\ y\\ z
\end{bmatrix} 
=w*\begin{bmatrix}
1\\ 0\\ 2
\end{bmatrix}.
$$

### Exercise 4a: 
Find out if the matrix is invertible.

In [14]:
# Checking if the matrix is invertible
matrix = np.array([[4,0,0],[10,0,-2],[0,2,-1]])
vector = np.array([1,0,2])
print(linalg.det(matrix))

16.000000000000007


### Exercise 4b: 
Solve the linear system with $w=1$.

In [18]:
# Finding a solution
result3 = linalg.solve(matrix,vector)
print(result3)
print(matrix @ result3)

[0.25  1.625 1.25 ]
[1. 0. 2.]


### Exercise 4c: 
Having 0.25 of a carbon atom doesn’t really make sense. Multiply the vector with the whole numbers from 1 to 10 to see when the solution consists of only whole numbers.

In [20]:
# Print out the multiples from 1 to 10
for i in range(1,11):
    resulti = linalg.solve(matrix,i * vector)
    print("w = ",i," result = ",resulti)

w =  1  result =  [0.25  1.625 1.25 ]
w =  2  result =  [0.5  3.25 2.5 ]
w =  3  result =  [0.75  4.875 3.75 ]
w =  4  result =  [1.  6.5 5. ]
w =  5  result =  [1.25  8.125 6.25 ]
w =  6  result =  [1.5  9.75 7.5 ]
w =  7  result =  [ 1.75  11.375  8.75 ]
w =  8  result =  [ 2. 13. 10.]
w =  9  result =  [ 2.25  14.625 11.25 ]
w =  10  result =  [ 2.5  16.25 12.5 ]


### Exercise 4d: 
Write up the balanced equation, in other words, what is $x,$ $y,$ $z,$ and $w$?
2,13,10,8

## Moral of the Story

NumPy's linear algebra module makes working with linear algebra easy. In many universities around the world, NumPy is used in courses for linear algebra. In Exercise 4 above, you saw that one can use NumPy to balance chemical equations. Many other applications of linear algebra exist and you can check out the article: https://medium.com/@jeremyjkun/here-s-just-a-fraction-of-what-you-can-do-with-linear-algebra-633383d4153f for more examples!