In [5]:
import numpy as np

# import txt file

In [6]:
data = np.loadtxt("data.txt", delimiter=",")
print(data)
print(data.mean())

[1. 2. 8. 9. 5. 1. 2. 8. 9. 5. 1. 2. 8. 9. 5. 1. 2. 8. 9. 5. 1. 2. 8. 9.
 5.]
5.0


# import csv file

In [13]:
data2 = np.loadtxt("data_csv.csv",delimiter=",")
print(data2)
print(np.isnan(data2).any())
print(data2.mean())
total_mean = np.nanmean(data2)
print(total_mean)

[[ 1.  2.  8.  9.]
 [nan  5.  1.  2.]
 [ 8.  9.  5.  1.]
 [ 8.  9. nan  5.]
 [ 1.  2.  8.  9.]
 [ 5.  1.  2.  8.]
 [ 9.  5.  2.  5.]]
True
nan
5.0


# save txt/csv file

In [23]:
np.nan_to_num(data2,copy = False,nan = total_mean)

array([[1., 2., 8., 9.],
       [5., 5., 1., 2.],
       [8., 9., 5., 1.],
       [8., 9., 5., 5.],
       [1., 2., 8., 9.],
       [5., 1., 2., 8.],
       [9., 5., 2., 5.]])

In [24]:
np.savetxt("newdata.txt",data2,delimiter=",",fmt="%.2f",header ="comment") 
np.savetxt("newdata.csv",data2,delimiter=",",fmt="%.2f",header ="comment") 

# load and save numpy objects

In [26]:
#save
daily_mean = data2.mean(axis = 1)
print(daily_mean)
np.save("daily_mean_new",daily_mean)

[5.   3.25 5.75 6.75 5.   4.   5.25]


In [27]:
#load
load_data =np.load("daily_mean_new.npy")
print(load_data)

[5.   3.25 5.75 6.75 5.   4.   5.25]


## compress two array in one file

In [ ]:
#save file and name the array
np.savez("rainy_days",load_mean = load_data,raw_data = data2)

In [34]:
#load
load_npz =np.load("rainy_days.npz")
print(load_npz.files)
load_mean = load_npz["load_mean"]
raw_data = load_npz["raw_data"]

['load_mean', 'raw_data']
